/* Generated By:JavaCC: Do not edit this line. FormulaGrammarConstants.java */
package edu.usc.ict.nl.kb.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FormulaGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LB = 5;
  /** RegularExpression Id. */
  int RB = 6;
  /** RegularExpression Id. */
  int PP = 7;
  /** RegularExpression Id. */
  int CM = 8;
  /** RegularExpression Id. */
  int EQ = 9;
  /** RegularExpression Id. */
  int CMP = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int LIST = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int ASSERT = 16;
  /** RegularExpression Id. */
  int IMPLY = 17;
  /** RegularExpression Id. */
  int ARIT = 18;
  /** RegularExpression Id. */
  int STRING = 19;
  /** RegularExpression Id. */
  int ID = 20;
  /** RegularExpression Id. */
  int ANY = 21;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int TEXT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"++\"",
    "\",\"",
    "\"=\"",
    "<CMP>",
    "\"or\"",
    "\"and\"",
    "\"assignlist\"",
    "<NOT>",
    "\"assign\"",
    "\"assert\"",
    "\"imply\"",
    "<ARIT>",
    "\"\\\'\"",
    "<ID>",
    "<ANY>",
  };

}
