/* Generated By:JavaCC: Do not edit this line. TextFormatGrammarConstants.java */
package edu.usc.ict.nl.dm.reward.model.textFormat;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TextFormatGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int AN = 10;
  /** RegularExpression Id. */
  int SPACE = 11;
  /** RegularExpression Id. */
  int RBRACE = 12;
  /** RegularExpression Id. */
  int LRB = 13;
  /** RegularExpression Id. */
  int RRB = 14;
  /** RegularExpression Id. */
  int VAR = 15;
  /** RegularExpression Id. */
  int GOAL = 16;
  /** RegularExpression Id. */
  int SEND = 17;
  /** RegularExpression Id. */
  int FORGET = 18;
  /** RegularExpression Id. */
  int TTCND = 19;
  /** RegularExpression Id. */
  int TOPIC = 20;
  /** RegularExpression Id. */
  int USER = 21;
  /** RegularExpression Id. */
  int SYSTEM = 22;
  /** RegularExpression Id. */
  int ISYSTEM = 23;
  /** RegularExpression Id. */
  int WAIT = 24;
  /** RegularExpression Id. */
  int SYSWAIT = 25;
  /** RegularExpression Id. */
  int EC = 26;
  /** RegularExpression Id. */
  int UI = 27;
  /** RegularExpression Id. */
  int SI = 28;
  /** RegularExpression Id. */
  int GV = 29;
  /** RegularExpression Id. */
  int RO = 30;
  /** RegularExpression Id. */
  int IS = 31;
  /** RegularExpression Id. */
  int NETWORK = 32;
  /** RegularExpression Id. */
  int FINAL = 33;
  /** RegularExpression Id. */
  int DAEMON = 34;
  /** RegularExpression Id. */
  int CONDITION = 35;
  /** RegularExpression Id. */
  int CE = 36;
  /** RegularExpression Id. */
  int OR = 37;
  /** RegularExpression Id. */
  int END = 38;
  /** RegularExpression Id. */
  int GOTOEND = 39;
  /** RegularExpression Id. */
  int NOP = 40;
  /** RegularExpression Id. */
  int IF = 41;
  /** RegularExpression Id. */
  int ELSE = 42;
  /** RegularExpression Id. */
  int CM = 43;
  /** RegularExpression Id. */
  int IGNORE = 44;
  /** RegularExpression Id. */
  int ID = 45;
  /** RegularExpression Id. */
  int ENDTEXT = 46;
  /** RegularExpression Id. */
  int URL = 47;
  /** RegularExpression Id. */
  int ANY = 48;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INSIDE_COMMENT = 1;
  /** Lexical state. */
  int TEXT = 2;
  /** Lexical state. */
  int INSIDE_COMMENT_TEXT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<LBRACE>",
    "<AN>",
    "<SPACE>",
    "<RBRACE>",
    "<LRB>",
    "<RRB>",
    "<VAR>",
    "<GOAL>",
    "<SEND>",
    "<FORGET>",
    "<TTCND>",
    "<TOPIC>",
    "\"user:\"",
    "\"system:\"",
    "\"isystem:\"",
    "<WAIT>",
    "<SYSWAIT>",
    "<EC>",
    "<UI>",
    "\"system initiative\"",
    "<GV>",
    "<RO>",
    "<IS>",
    "<NETWORK>",
    "<FINAL>",
    "<DAEMON>",
    "<CONDITION>",
    "<CE>",
    "<OR>",
    "<END>",
    "<GOTOEND>",
    "<NOP>",
    "<IF>",
    "<ELSE>",
    "<CM>",
    "<IGNORE>",
    "<ID>",
    "<ENDTEXT>",
    "<URL>",
    "<ANY>",
    "\"*/\"",
    "<token of kind 50>",
  };

}
