//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 12:34:04 PM PDT 
//


package edu.usc.ict.perception.pml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}layer1" minOccurs="0"/>
 *         &lt;element ref="{}layer2" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gender" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="age" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "layer1",
    "layer2"
})
@XmlRootElement(name = "body")
public class Body {

    protected Layer1 layer1;
    protected Layer2 layer2;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    protected double gender;
    @XmlAttribute(required = true)
    protected double age;

    /**
     * Gets the value of the layer1 property.
     * 
     * @return
     *     possible object is
     *     {@link Layer1 }
     *     
     */
    public Layer1 getLayer1() {
        return layer1;
    }

    /**
     * Sets the value of the layer1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Layer1 }
     *     
     */
    public void setLayer1(Layer1 value) {
        this.layer1 = value;
    }

    /**
     * Gets the value of the layer2 property.
     * 
     * @return
     *     possible object is
     *     {@link Layer2 }
     *     
     */
    public Layer2 getLayer2() {
        return layer2;
    }

    /**
     * Sets the value of the layer2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Layer2 }
     *     
     */
    public void setLayer2(Layer2 value) {
        this.layer2 = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     */
    public double getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     */
    public void setGender(double value) {
        this.gender = value;
    }

    /**
     * Gets the value of the age property.
     * 
     */
    public double getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     */
    public void setAge(double value) {
        this.age = value;
    }

}
