//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 12:34:04 PM PDT 
//


package edu.usc.ict.perception.pml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}gazeCategoryHorizontal"/>
 *         &lt;element ref="{}gazeCategoryVertical"/>
 *         &lt;element ref="{}gazeCategoryDirection"/>
 *         &lt;element ref="{}confidence" minOccurs="0"/>
 *         &lt;element ref="{}conf_str" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gazeCategoryHorizontal",
    "gazeCategoryVertical",
    "gazeCategoryDirection",
    "confidence",
    "confStr"
})
@XmlRootElement(name = "faceGaze")
public class FaceGaze {

    @XmlElement(required = true)
    protected String gazeCategoryHorizontal;
    @XmlElement(required = true)
    protected String gazeCategoryVertical;
    @XmlElement(required = true)
    protected String gazeCategoryDirection;
    protected Double confidence;
    @XmlElement(name = "conf_str")
    protected String confStr;

    /**
     * Gets the value of the gazeCategoryHorizontal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGazeCategoryHorizontal() {
        return gazeCategoryHorizontal;
    }

    /**
     * Sets the value of the gazeCategoryHorizontal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGazeCategoryHorizontal(String value) {
        this.gazeCategoryHorizontal = value;
    }

    /**
     * Gets the value of the gazeCategoryVertical property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGazeCategoryVertical() {
        return gazeCategoryVertical;
    }

    /**
     * Sets the value of the gazeCategoryVertical property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGazeCategoryVertical(String value) {
        this.gazeCategoryVertical = value;
    }

    /**
     * Gets the value of the gazeCategoryDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGazeCategoryDirection() {
        return gazeCategoryDirection;
    }

    /**
     * Sets the value of the gazeCategoryDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGazeCategoryDirection(String value) {
        this.gazeCategoryDirection = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setConfidence(Double value) {
        this.confidence = value;
    }

    /**
     * Gets the value of the confStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfStr() {
        return confStr;
    }

    /**
     * Sets the value of the confStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfStr(String value) {
        this.confStr = value;
    }

}
