//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 12:34:04 PM PDT 
//


package edu.usc.ict.perception.pml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}presence" minOccurs="0"/>
 *         &lt;element ref="{}smileFrequency" minOccurs="0"/>
 *         &lt;element ref="{}activity" minOccurs="0"/>
 *         &lt;element ref="{}attention" minOccurs="0"/>
 *         &lt;element ref="{}agreement" minOccurs="0"/>
 *         &lt;element ref="{}engagement" minOccurs="0"/>
 *         &lt;element ref="{}anxiety" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "presence",
    "smileFrequency",
    "activity",
    "attention",
    "agreement",
    "engagement",
    "anxiety"
})
@XmlRootElement(name = "layer1")
public class Layer1 {

    protected Presence presence;
    protected SmileFrequency smileFrequency;
    protected Activity activity;
    protected Attention attention;
    protected Agreement agreement;
    protected Engagement engagement;
    protected Anxiety anxiety;

    /**
     * Gets the value of the presence property.
     * 
     * @return
     *     possible object is
     *     {@link Presence }
     *     
     */
    public Presence getPresence() {
        return presence;
    }

    /**
     * Sets the value of the presence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Presence }
     *     
     */
    public void setPresence(Presence value) {
        this.presence = value;
    }

    /**
     * Gets the value of the smileFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link SmileFrequency }
     *     
     */
    public SmileFrequency getSmileFrequency() {
        return smileFrequency;
    }

    /**
     * Sets the value of the smileFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmileFrequency }
     *     
     */
    public void setSmileFrequency(SmileFrequency value) {
        this.smileFrequency = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link Activity }
     *     
     */
    public Activity getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Activity }
     *     
     */
    public void setActivity(Activity value) {
        this.activity = value;
    }

    /**
     * Gets the value of the attention property.
     * 
     * @return
     *     possible object is
     *     {@link Attention }
     *     
     */
    public Attention getAttention() {
        return attention;
    }

    /**
     * Sets the value of the attention property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attention }
     *     
     */
    public void setAttention(Attention value) {
        this.attention = value;
    }

    /**
     * Gets the value of the agreement property.
     * 
     * @return
     *     possible object is
     *     {@link Agreement }
     *     
     */
    public Agreement getAgreement() {
        return agreement;
    }

    /**
     * Sets the value of the agreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agreement }
     *     
     */
    public void setAgreement(Agreement value) {
        this.agreement = value;
    }

    /**
     * Gets the value of the engagement property.
     * 
     * @return
     *     possible object is
     *     {@link Engagement }
     *     
     */
    public Engagement getEngagement() {
        return engagement;
    }

    /**
     * Sets the value of the engagement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Engagement }
     *     
     */
    public void setEngagement(Engagement value) {
        this.engagement = value;
    }

    /**
     * Gets the value of the anxiety property.
     * 
     * @return
     *     possible object is
     *     {@link Anxiety }
     *     
     */
    public Anxiety getAnxiety() {
        return anxiety;
    }

    /**
     * Sets the value of the anxiety property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anxiety }
     *     
     */
    public void setAnxiety(Anxiety value) {
        this.anxiety = value;
    }

}
