//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 12:34:04 PM PDT 
//


package edu.usc.ict.perception.pml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}posture" maxOccurs="10" minOccurs="0"/>
 *         &lt;element ref="{}faceGesture" maxOccurs="10" minOccurs="0"/>
 *         &lt;element ref="{}headPose" minOccurs="0"/>
 *         &lt;element ref="{}handPoseLeft" minOccurs="0"/>
 *         &lt;element ref="{}handPoseRight" minOccurs="0"/>
 *         &lt;element ref="{}faceGaze" minOccurs="0"/>
 *         &lt;element ref="{}eyeGaze" minOccurs="0"/>
 *         &lt;element ref="{}headGesture" maxOccurs="10" minOccurs="0"/>
 *         &lt;element ref="{}handGesture" maxOccurs="10" minOccurs="0"/>
 *         &lt;element ref="{}armLeft" maxOccurs="10" minOccurs="0"/>
 *         &lt;element ref="{}armRight" maxOccurs="10" minOccurs="0"/>
 *         &lt;element ref="{}speechFraction" maxOccurs="10" minOccurs="0"/>
 *         &lt;element ref="{}speechVariation" maxOccurs="10" minOccurs="0"/>
 *         &lt;element ref="{}speechRate" maxOccurs="10" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "posture",
    "faceGesture",
    "headPose",
    "handPoseLeft",
    "handPoseRight",
    "faceGaze",
    "eyeGaze",
    "headGesture",
    "handGesture",
    "armLeft",
    "armRight",
    "speechFraction",
    "speechVariation",
    "speechRate"
})
@XmlRootElement(name = "layer2")
public class Layer2 {

    protected List<Posture> posture;
    protected List<FaceGesture> faceGesture;
    protected HeadPose headPose;
    protected HandPoseLeft handPoseLeft;
    protected HandPoseRight handPoseRight;
    protected FaceGaze faceGaze;
    protected EyeGaze eyeGaze;
    protected List<HeadGesture> headGesture;
    protected List<HandGesture> handGesture;
    protected List<ArmLeft> armLeft;
    protected List<ArmRight> armRight;
    protected List<SpeechFraction> speechFraction;
    protected List<SpeechVariation> speechVariation;
    protected List<SpeechRate> speechRate;

    /**
     * Gets the value of the posture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the posture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPosture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Posture }
     * 
     * 
     */
    public List<Posture> getPosture() {
        if (posture == null) {
            posture = new ArrayList<Posture>();
        }
        return this.posture;
    }

    /**
     * Gets the value of the faceGesture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faceGesture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaceGesture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FaceGesture }
     * 
     * 
     */
    public List<FaceGesture> getFaceGesture() {
        if (faceGesture == null) {
            faceGesture = new ArrayList<FaceGesture>();
        }
        return this.faceGesture;
    }

    /**
     * Gets the value of the headPose property.
     * 
     * @return
     *     possible object is
     *     {@link HeadPose }
     *     
     */
    public HeadPose getHeadPose() {
        return headPose;
    }

    /**
     * Sets the value of the headPose property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadPose }
     *     
     */
    public void setHeadPose(HeadPose value) {
        this.headPose = value;
    }

    /**
     * Gets the value of the handPoseLeft property.
     * 
     * @return
     *     possible object is
     *     {@link HandPoseLeft }
     *     
     */
    public HandPoseLeft getHandPoseLeft() {
        return handPoseLeft;
    }

    /**
     * Sets the value of the handPoseLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandPoseLeft }
     *     
     */
    public void setHandPoseLeft(HandPoseLeft value) {
        this.handPoseLeft = value;
    }

    /**
     * Gets the value of the handPoseRight property.
     * 
     * @return
     *     possible object is
     *     {@link HandPoseRight }
     *     
     */
    public HandPoseRight getHandPoseRight() {
        return handPoseRight;
    }

    /**
     * Sets the value of the handPoseRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandPoseRight }
     *     
     */
    public void setHandPoseRight(HandPoseRight value) {
        this.handPoseRight = value;
    }

    /**
     * Gets the value of the faceGaze property.
     * 
     * @return
     *     possible object is
     *     {@link FaceGaze }
     *     
     */
    public FaceGaze getFaceGaze() {
        return faceGaze;
    }

    /**
     * Sets the value of the faceGaze property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaceGaze }
     *     
     */
    public void setFaceGaze(FaceGaze value) {
        this.faceGaze = value;
    }

    /**
     * Gets the value of the eyeGaze property.
     * 
     * @return
     *     possible object is
     *     {@link EyeGaze }
     *     
     */
    public EyeGaze getEyeGaze() {
        return eyeGaze;
    }

    /**
     * Sets the value of the eyeGaze property.
     * 
     * @param value
     *     allowed object is
     *     {@link EyeGaze }
     *     
     */
    public void setEyeGaze(EyeGaze value) {
        this.eyeGaze = value;
    }

    /**
     * Gets the value of the headGesture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headGesture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeadGesture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HeadGesture }
     * 
     * 
     */
    public List<HeadGesture> getHeadGesture() {
        if (headGesture == null) {
            headGesture = new ArrayList<HeadGesture>();
        }
        return this.headGesture;
    }

    /**
     * Gets the value of the handGesture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the handGesture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHandGesture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HandGesture }
     * 
     * 
     */
    public List<HandGesture> getHandGesture() {
        if (handGesture == null) {
            handGesture = new ArrayList<HandGesture>();
        }
        return this.handGesture;
    }

    /**
     * Gets the value of the armLeft property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the armLeft property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArmLeft().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArmLeft }
     * 
     * 
     */
    public List<ArmLeft> getArmLeft() {
        if (armLeft == null) {
            armLeft = new ArrayList<ArmLeft>();
        }
        return this.armLeft;
    }

    /**
     * Gets the value of the armRight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the armRight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArmRight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArmRight }
     * 
     * 
     */
    public List<ArmRight> getArmRight() {
        if (armRight == null) {
            armRight = new ArrayList<ArmRight>();
        }
        return this.armRight;
    }

    /**
     * Gets the value of the speechFraction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the speechFraction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpeechFraction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpeechFraction }
     * 
     * 
     */
    public List<SpeechFraction> getSpeechFraction() {
        if (speechFraction == null) {
            speechFraction = new ArrayList<SpeechFraction>();
        }
        return this.speechFraction;
    }

    /**
     * Gets the value of the speechVariation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the speechVariation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpeechVariation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpeechVariation }
     * 
     * 
     */
    public List<SpeechVariation> getSpeechVariation() {
        if (speechVariation == null) {
            speechVariation = new ArrayList<SpeechVariation>();
        }
        return this.speechVariation;
    }

    /**
     * Gets the value of the speechRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the speechRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpeechRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpeechRate }
     * 
     * 
     */
    public List<SpeechRate> getSpeechRate() {
        if (speechRate == null) {
            speechRate = new ArrayList<SpeechRate>();
        }
        return this.speechRate;
    }

}
