//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 12:34:04 PM PDT 
//


package edu.usc.ict.perception.pml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="rotX" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;minInclusive value="-180"/>
 *             &lt;maxInclusive value="180"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="rotY" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;minInclusive value="-180"/>
 *             &lt;maxInclusive value="180"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="rotZ" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;minInclusive value="-180"/>
 *             &lt;maxInclusive value="180"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "rotation")
public class Rotation {

    @XmlAttribute(required = true)
    protected double rotX;
    @XmlAttribute(required = true)
    protected double rotY;
    @XmlAttribute(required = true)
    protected double rotZ;

    /**
     * Gets the value of the rotX property.
     * 
     */
    public double getRotX() {
        return rotX;
    }

    /**
     * Sets the value of the rotX property.
     * 
     */
    public void setRotX(double value) {
        this.rotX = value;
    }

    /**
     * Gets the value of the rotY property.
     * 
     */
    public double getRotY() {
        return rotY;
    }

    /**
     * Sets the value of the rotY property.
     * 
     */
    public void setRotY(double value) {
        this.rotY = value;
    }

    /**
     * Gets the value of the rotZ property.
     * 
     */
    public double getRotZ() {
        return rotZ;
    }

    /**
     * Sets the value of the rotZ property.
     * 
     */
    public void setRotZ(double value) {
        this.rotZ = value;
    }

}
