//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 12:34:04 PM PDT 
//


package edu.usc.ict.perception.pml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}speechFractionValue"/>
 *         &lt;element name="speechInterval" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element ref="{}confidence" minOccurs="0"/>
 *         &lt;element ref="{}conf_str" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "speechFractionValue",
    "speechInterval",
    "startTime",
    "endTime",
    "confidence",
    "confStr"
})
@XmlRootElement(name = "speechFraction")
public class SpeechFraction {

    protected double speechFractionValue;
    protected double speechInterval;
    protected double startTime;
    protected double endTime;
    protected Double confidence;
    @XmlElement(name = "conf_str")
    protected String confStr;

    /**
     * Gets the value of the speechFractionValue property.
     * 
     */
    public double getSpeechFractionValue() {
        return speechFractionValue;
    }

    /**
     * Sets the value of the speechFractionValue property.
     * 
     */
    public void setSpeechFractionValue(double value) {
        this.speechFractionValue = value;
    }

    /**
     * Gets the value of the speechInterval property.
     * 
     */
    public double getSpeechInterval() {
        return speechInterval;
    }

    /**
     * Sets the value of the speechInterval property.
     * 
     */
    public void setSpeechInterval(double value) {
        this.speechInterval = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     */
    public double getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     */
    public void setStartTime(double value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     */
    public double getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     */
    public void setEndTime(double value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setConfidence(Double value) {
        this.confidence = value;
    }

    /**
     * Gets the value of the confStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfStr() {
        return confStr;
    }

    /**
     * Sets the value of the confStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfStr(String value) {
        this.confStr = value;
    }

}
