/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package edu.usc.ict.nl.nlg.lf.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LB = 5;
  /** RegularExpression Id. */
  int RB = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int NEG = 8;
  /** RegularExpression Id. */
  int CM = 9;
  /** RegularExpression Id. */
  int ID = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"and\"",
    "\"negated\"",
    "\",\"",
    "<ID>",
  };

}
